seed_everything: 37
trainer:

  check_val_every_n_epoch: 1

  max_epochs: 50

  default_root_dir: ./drive/MyDrive/DeltaEJPEG/base

  accelerator: gpu
  devices: 1

  log_every_n_steps: 1

  callbacks:
    - class_path: pytorch_lightning.callbacks.RichProgressBar
      init_args:
        theme:
          class_path: pytorch_lightning.callbacks.progress.rich_progress.RichProgressBarTheme
          init_args:
            metrics_text_delimiter: " | "

    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
        save_top_k: 1
        save_last: True
        filename: '{epoch:02d}-{val_loss:.2f}'
        dirpath: ./drive/MyDrive/DeltaEJPEG/base/checkpoints

data:
  data_dir: ./dataset
  batch_size: 8
