seed_everything: 37
trainer:

  check_val_every_n_epoch: 1

  max_epochs: 100

  default_root_dir: ./drive/MyDrive/DeltaEJPEG/ff-naive-other-32-q10-lpips-4convs

  accelerator: gpu
  devices: 1

  log_every_n_steps: 1

#  detect_anomaly: True

  callbacks:
    - class_path: pytorch_lightning.callbacks.ModelCheckpoint
      init_args:
        monitor: val_lpips_alex
        mode: min
        save_top_k: 1
        save_last: True
        filename: '{epoch:02d}-{val_lpips_alex:.2f}'

    - class_path: pytorch_lightning.callbacks.RichProgressBar

data:
  data_dir: ./dataset
  batch_size: 4

model:
  downsample:
    class_path: jpeg.ds.naive.NaiveDownsample
#    class_path: jpeg.ds.conv.ConvDownsample
#    init_args:
#      channels: 64
#      init: False
#      clamp: False
  upsample:
#    class_path: jpeg.ds.naive.NaiveUpsample
    class_path: jpeg.ds.conv.OtherUpsample
    init_args:
      channels: 32
      n_conv: 4
#      clamp: False
  quality: 10
  lr: 1e-3
  weight_decay: 1e-3
  loss_dict:
    lpips_alex: 1
