seed_everything: 37
trainer:

  check_val_every_n_epoch: 1

  max_epochs: 50

  default_root_dir: ./drive/MyDrive/DeltaEJPEG/base

  accelerator: gpu
  devices: 1

  log_every_n_steps: 1

  callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      monitor: val_loss
      mode: min
      save_top_k: 1
      save_last: True
      filename: '{epoch:02d}-{val_loss:.2f}'
      dirpath: ./drive/MyDrive/DeltaEJPEG/base/checkpoints

  - class_path: pytorch_lightning.callbacks.RichProgressBar

data:
  data_dir: ./dataset
  batch_size: 8

model:
  downsample:
    class_path: jpeg.ds.conv.ConvDownsample
    init_args:
      channels: 128
#      init: False
      clamp: False
  upsample:
    class_path: jpeg.ds.conv.ConvUpsample
    init_args:
      channels: 128
#      init: False
      final_kernel_size: null
      clamp: False
  lr: 1e-2
